// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "translation": {
    "account": {
      "continueShopping": "Продолжить покупки",
      "delivery": "Доставка: {{address}}",
      "empty": {
        "action": "Перейти в каталог",
        "text": "Оформленные заказы появятся здесь вместе с составом, ценами на момент покупки и итогом.",
        "title": "Заказов пока нет"
      },
      "loadFailed": "Не удалось загрузить заказы. Обновите страницу.",
      "orderNumber": "Заказ №{{id}}",
      "pickup": "Самовывоз",
      "status": {
        "paid": "Оплачен"
      },
      "table": {
        "priceAtPurchase": "Цена покупки",
        "product": "Товар",
        "quantity": "Кол-во",
        "sum": "Сумма"
      },
      "title": "Личный кабинет",
      "total": "Итого: {{total}}"
    },
    "app": {
      "brand": "Комплектующие",
      "footer": "Магазин комплектующих для ПК — учебный проект Хекслета"
    },
    "auth": {
      "emailLabel": "Email",
      "emailPlaceholder": "you@example.com",
      "invalidEmail": "Укажите корректный email",
      "passwordLabel": "Пароль",
      "passwordPlaceholder": "Не короче шести символов",
      "shortPassword": "Пароль короче шести символов",
      "signIn": {
        "submit": "Войти",
        "subtitle": "Войдите, чтобы продолжить оформление заказа.",
        "switchLink": "Зарегистрироваться",
        "switchPrompt": "Нет аккаунта? ",
        "title": "Вход"
      },
      "signUp": {
        "submit": "Зарегистрироваться",
        "subtitle": "Аккаунт нужен, чтобы оформить заказ и видеть историю покупок.",
        "switchLink": "Войти",
        "switchPrompt": "Уже есть аккаунт? ",
        "title": "Регистрация"
      }
    },
    "availability": {
      "inStock": "В наличии",
      "outOfStock": "Нет в наличии"
    },
    "cart": {
      "checkout": "Оформить заказ",
      "empty": {
        "action": "Перейти в каталог",
        "text": "Выберите товары в каталоге — они появятся здесь и переживут перезагрузку страницы.",
        "title": "Корзина пуста"
      },
      "goneHint": "Товара больше нет в каталоге — удалите позицию",
      "outOfStockHint": "Нет в наличии — заказ с этим товаром не пройдёт",
      "perUnit": "{{price}} за штуку",
      "quantity": "Количество",
      "remove": "Удалить",
      "summary": {
        "items": "Товаров",
        "note": "Окончательную сумму посчитает сервер по актуальным ценам.",
        "title": "Итог",
        "total": "К оплате"
      },
      "title": "Корзина",
      "unknownProduct": "Товар недоступен"
    },
    "catalog": {
      "addToCart": "В корзину",
      "empty": {
        "action": "Показать все товары",
        "text": "Под выбранные фильтры не подошёл ни один товар. Измените условия или сбросьте фильтры.",
        "title": "Ничего не найдено"
      },
      "filters": {
        "allCategories": "Все категории",
        "availableOnly": "Только в наличии",
        "category": "Категория",
        "name": "Название",
        "namePlaceholder": "Например, RTX",
        "priceMax": "Цена до, ₽",
        "priceMaxPlaceholder": "200 000",
        "priceMin": "Цена от, ₽",
        "priceMinPlaceholder": "0",
        "reset": "Сбросить фильтры"
      },
      "found": "Найдено товаров: {{total}}",
      "loadFailed": "Не удалось загрузить каталог. Обновите страницу.",
      "subtitle": "Видеокарты, процессоры и материнские платы — с фильтрами по категории, цене и наличию.",
      "title": "Комплектующие для ПК"
    },
    "checkout": {
      "addressLabel": "Адрес доставки",
      "addressPlaceholder": "улица, дом, квартира",
      "addressRequired": "При доставке адрес обязателен",
      "delivery": "Доставка",
      "errorTitle": "Заказ не оформлен",
      "itemFallback": "Товар {{id}}",
      "items": "Состав заказа",
      "method": "Способ получения",
      "nameLabel": "Имя получателя",
      "namePlaceholder": "Иван Петров",
      "nameRequired": "Укажите имя получателя",
      "phoneLabel": "Телефон",
      "phonePlaceholder": "+7 999 000-11-22",
      "phoneRequired": "Укажите телефон",
      "pickup": "Самовывоз",
      "pickupNote": "Самовывоз из единственного пункта выдачи — адрес указывать не нужно.",
      "previewNote": "Окончательную сумму посчитает сервер по актуальным ценам товаров.",
      "previewTotal": "Предварительный итог",
      "section": "Получение",
      "submit": "Оформить заказ",
      "title": "Оформление заказа"
    },
    "errors": {
      "addressRequired": "При доставке нужно указать адрес",
      "blank": "Запрос не выполнен",
      "emailTaken": "Пользователь с таким email уже зарегистрирован",
      "internalError": "На сервере что-то сломалось. Попробуйте позже.",
      "invalidCredentials": "Неверный email или пароль",
      "network": "Не удалось выполнить запрос. Попробуйте ещё раз.",
      "notFound": "Запрашиваемые данные не найдены",
      "unauthorized": "Нужно войти в аккаунт",
      "unavailableItems": "Часть товаров недоступна для заказа",
      "validationError": "Проверьте введённые данные"
    },
    "home": {
      "loadFailed": "Не удалось загрузить подборки. Обновите страницу.",
      "promoEmpty": "Подборок пока нет — весь ассортимент есть в каталоге.",
      "promoTitle": "Выбор магазина",
      "subtitle": "Видеокарты, процессоры и материнские платы в наличии. Собираем подборки под задачу, чтобы не выбирать из всего каталога сразу.",
      "title": "Комплектующие для ПК с доставкой по городу",
      "toCatalog": "Перейти в каталог"
    },
    "nav": {
      "account": "Кабинет",
      "cart": "Корзина",
      "catalog": "Каталог",
      "signIn": "Вход",
      "signOut": "Выйти",
      "signUp": "Регистрация"
    },
    "orderSuccess": {
      "backToCatalog": "Вернуться в каталог",
      "delivery": "доставка на адрес {{address}}",
      "items": "Состав заказа",
      "myOrders": "Мои заказы",
      "pickup": "самовывоз",
      "recipient": "Получатель: {{name}}, {{phone}}",
      "title": "Заказ №{{id}} оформлен",
      "total": "Итого"
    },
    "product": {
      "addToCart": "В корзину",
      "added": "Товар в корзине.",
      "backToCatalog": "Вернуться в каталог",
      "facts": {
        "payment": "Оплата при оформлении заказа",
        "price": "Цена указана в рублях, без копеек",
        "shipping": "Доставка по городу или самовывоз"
      },
      "goToCheckout": "Перейти к оформлению",
      "noImage": "Нет изображения",
      "notFound": "Такого товара нет в каталоге.",
      "unavailable": "Нет в наличии"
    }
  }
}
